### ISSUE TITLE
t.removeAttribute is not a function

### ISSUE THREAD

**Issue by linonetwo** [Gk0Wk/TiddlySeq#10]
```
uncaught TypeError: t.removeAttribute is not a function
    at ElixirWidget.getThemeButton (widget.js:49:20337)
    at ElixirWidget.render (widget.js:49:16666)
    at Widget.renderChildren (widget.js:632:15)
    at TranscludeWidget.render (transclude.js:36:7)
    at Widget.renderChildren (widget.js:632:15)
    at TranscludeWidget.render (transclude.js:36:7)
    at Widget.renderChildren (widget.js:632:15)
    at RevealWidget.render (reveal.js:49:7)
    at Widget.renderChildren (widget.js:632:15)
    at ImportVariablesWidget.render (importvariables.js:36:7)
logger.js:56 syncer-browser-tiddlyweb: Checking dirty status
logger.js:56 syncer-browser-tiddlyweb: Dispatching 'save' task: 2023-6-14
2logger.js:56 syncer-browser-tiddlyweb: Checking dirty status
logger.js:56 syncer-browser-tiddlyweb: Dispatching 'delete' task: Draft of '2023-6-14' by 林一二
boot.js:214 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
$tw.utils.error @ boot.js:214
popup.js:163 Uncaught TypeError: Cannot read properties of undefined (reading 'style')
    at Reveal.refresh (popup.js:163:18)
    at Widget.refreshChildren (widget.js:705:27)
    at ImportVariablesWidget.refresh (importvariables.js:133:15)
    at Widget.refreshChildren (widget.js:705:27)
    at TranscludeWidget.refresh (transclude.js:431:15)
    at Widget.refreshChildren (widget.js:705:27)
    at ListItemWidget.refresh (list.js:364:14)
    at ListWidget.handleListChanges (list.js:265:39)
    at ListWidget.refresh (list.js:164:17)
    at Widget.refreshChildren (widget.js:705:27)
```

```
created: 20230614113511759
creator: 林一二
modified: 20230614113517963
modifier: 林一二
tags: 想法
title: 2023-6-14
type: text/vnd.tiddlywiki

<$mindmap field="map" />
```

尝试让 map 保存到当前条目的 map 字段，然后点击✅保存就报错了

**Comment by Gk0Wk** [comment]
已修复
