### ISSUE TITLE
toc 插件改用 focused tiddler 插件

### ISSUE THREAD

**Issue by linonetwo** [Gk0Wk/TiddlySeq#18]
toc 插件还需要 hotzone 插件吗？我记得你开发了一个替代 hotzone 的 focused tiddler 插件吧？

主要是 hotzone 有bug，如果启动前在别的 layout 里，会报错

```js
hotzone.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'children')
    at l (hotzone.js:10:1068)
    at eval (hotzone.js:10:1521)
```

```
var i = document.getElementsByClassName(t.classNames.storyRiver)[0];
var f = i.children;
```

**Comment by dongrentianyu** [comment]
应该是不需要了。我删除了 hotzone 插件也能正常使用。
