### ISSUE TITLE
notionpage-covericon插件可能会导致tiddlywiki --load ./mywiki.html --savewikifolder ./mywikifolder命令失败

### ISSUE THREAD

**Issue by Zacharia2** [Gk0Wk/TiddlySeq#5]
当我在任意平台（Win10、Linux）执行这个命令转换含有notionpage-covericon插件的官方空白wiki：[mywiki.zip](https://github.com/tiddly-gittly/TidGi-Desktop/files/9996524/mywiki.zip) （解压后即可查看）时：tiddlywiki --load ./mywiki.html --savewikifolder ./mywikifolder

发生以下错误：

{"level":"error","message":"Tiddlywiki booted failed with error Cannot read properties of undefined (reading 'replace') 
TypeError: Cannot read properties of undefined (reading 'replace')
 at Object.exports.generateTiddlerFilepath ($:/core/modules/utils/filesystem.js:344:23)
 at Object.exports.generateTiddlerFileInfo ($:/core/modules/utils/filesystem.js:278:32)
 at WikiFolderMaker.saveTiddler ($:/core/modules/commands/savewikifolder.js:168:27)
 at $:/core/modules/commands/savewikifolder.js:156:8
 at Object.$tw.utils.each (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:155:12)
 at WikiFolderMaker.saveCustomPlugin ($:/core/modules/commands/savewikifolder.js:155:12)
 at $:/core/modules/commands/savewikifolder.js:99:12
 at Object.$tw.utils.each (/home/whitefall/桌面/TidGi-Desktop/node_modules/@tiddlygit/tiddlywiki/boot/boot.js:146:12)
 at WikiFolderMaker.save ($:/core/modules/commands/savewikifolder.js:79:12)
 at Command.execute ($:/core/modules/commands/savewikifolder.js:39:25)","timestamp":"2022-11-12T03:12:43.276Z"}

删除该插件后，Cannot read properties of undefined (reading 'replace')错误消失。

filesystem.js:344：generateTiddlerFilepath方法中局部变量filepath 由 title参数赋值，找到调用 title参数的实际参数为 tiddler.fields.title，由generateTiddlerFileInfo方法的tiddler参数提供的。

savewikifolder.js:168：找到generateTiddlerFileInfo的函数调用，并找到其参数tiddler，由方法WikiFolderMaker.prototype.saveTiddler的参数tiddler提供。找到此函数的调用者WikiFolderMaker.prototype.saveCustomPlugin（pluginTiddler）

```
var pluginTiddlers = $tw.utils.parseJSONSafe(pluginTiddler.fields.text).tiddlers; // A hashmap of tiddlers in the plugin
	$tw.utils.each(pluginTiddlers,function(tiddler) {
		self.saveTiddler(directory,new $tw.Tiddler(tiddler));//在这个地方调用的。
	});
```

然后就不知道咋弄了，我一直找不到那个未定义的的那个条目的那个标题或字段。所以就根据打印log查看最后一个输出的插件或条目信息，手动实验禁用或者删除，发现notionpage-covericon插件导致的问题。

这个是空白的wiki文件，只安装了notionpage-covericon插件，但是无法使用HTML转wiki文件夹命令：[mywiki.zip](https://github.com/tiddly-gittly/TidGi-Desktop/files/9996524/mywiki.zip) （解压后即可查看）

```
tiddlywiki --load ./mywiki.html --savewikifolder ./mywikifolder
```

**Comment by Zacharia2** [comment]
林一二的回答：https://github.com/tiddly-gittly/TidGi-Desktop/issues/292#issuecomment-1312683984

**Comment by Zacharia2** [comment]
林一二的回答：https://github.com/tiddly-gittly/TidGi-Desktop/issues/292#issuecomment-1312683984

**Comment by Gk0Wk** [comment]
那先把 title 加上
